sudo: false
language: python
python:
  - "2.7"
cache:
  - pip
before_install:
  - pip install --upgrade pip
install:
  # Try install molo.core with packaging fixes
  - pip install git+https://github.com/praekelt/molo.git@packaging-updates#egg=molo.core
  - pip install -e .
  - pip install -r requirements-dev.txt
  - pip install coveralls
script:
  - flake8
  # Ensure plural expressions are not allowed in PO files
  # Disabled: need to find a better way of doing this
  #- grep -Rq "plural=EXPRESSION" --include \*.po locale/
  - py.test
  # Check that the molo.core version in requirements.txt matches the version in the Docker image
  - \[ "$(sed -nE 's/^molo\.core==(.*)$/\1/p' requirements.txt)" = "$(sed -nE 's/^FROM .*:(.*)-onbuild$/\1/p' Dockerfile)" \]
after_success:
  - coveralls
